# shellcheck shell=bash
# apps/devterm/render.sh — sourceable render library (child 4, P1a
# extract-verify-swap). Functions only, no top-level execution. Each unit
# function body is a VERBATIM copy of the heredoc it replaces, proven
# byte-identical to the inline text by install/test-render-parity.sh before
# any write site moves (P1b).
#
# The nginx fragment is not a heredoc in install.sh (it composes
# gate/nginx-lib.sh's emit_owner_gate + emit_https_redirect), so
# render_devterm_nginx is a thin wrapper around those calls — included for a
# single P1b write-site swap.

# render_devterm_exec_shim RESOLVED_ABSOLUTE_TARGET
# The installer writes this to a same-directory temporary file and atomically renames
# it over the legacy terminal command. shlex.quote keeps unusual but valid absolute
# paths safe without leaving an AIRLOCK_* variable for an interactive shell to resolve.
render_devterm_exec_shim() {
  python3 - "$1" <<'PY'
import shlex
import sys
print("#!/bin/sh")
print('exec %s "$@"' % shlex.quote(sys.argv[1]))
PY
}

# render_devterm_unit_ttyd DEVTERM_LANG TTYD_PORT TTYD_BIN FONT_SIZE
render_devterm_unit_ttyd() {
  local DEVTERM_LANG="$1" TTYD_PORT="$2" TTYD_BIN="$3" FONT_SIZE="$4"
  cat <<UNIT
[Unit]
Description=airlock devterm — ttyd PTY backend (127.0.0.1:${TTYD_PORT})
After=network.target

[Service]
Environment=LANG=${DEVTERM_LANG}
Environment=LC_CTYPE=${DEVTERM_LANG}
# -a: pass ?arg= to the shell as its session name; -W: writable; -P 2: fast dead-conn detect
ExecStart=${TTYD_BIN} -i 127.0.0.1 -p ${TTYD_PORT} -P 2 -W -a -t fontSize=${FONT_SIZE} %h/.local/bin/devterm-shell
KillMode=process
Restart=on-failure
RestartSec=2

[Install]
WantedBy=default.target
UNIT
}

# render_devterm_unit_gate BACKEND_PORT gate_env PY GATE_PY
# gate_env is the pre-built multi-line "Environment=K=V\n..." block (built by
# install.sh's add_env helper — unchanged, still outside this library).
render_devterm_unit_gate() {
  local BACKEND_PORT="$1" gate_env="$2" PY="$3" GATE_PY="$4"
  cat <<UNIT
[Unit]
Description=airlock devterm-gate — custom client + API, proxies to ttyd (127.0.0.1:${BACKEND_PORT})
After=network.target airlock-devterm.service
Wants=airlock-devterm.service

[Service]
Type=simple
${gate_env}ExecStart=${PY} ${GATE_PY}
# KillMode=process, same reason as the ttyd unit: the gate starts a detached
# \`codex login --device-auth\` that must outlive a redeploy. setsid does not leave the
# cgroup, so the default (control-group) kills the pending login while the user is
# entering the code on their phone — and the old credential is already backed out.
KillMode=process
Restart=on-failure
RestartSec=2

[Install]
WantedBy=default.target
UNIT
}

# render_devterm_nginx GATE_PORT BACKEND_PORT [ACCOUNT_PANEL_DIR]
# Trailing args beyond those are ignored: D-DEVTERM-9900 retired the plaintext redirect.
#
# ACCOUNT_PANEL_DIR (optional) is the platform's account-panel asset directory in the
# webroot. When given, this gate serves panel.html and accounts.js from THERE instead
# of from devterm's own web root — the panel is a platform asset (ACCT_OWN), and an
# alias keeps one deployed copy rather than a per-app duplicate that can drift. Same
# arrangement emit_owner_gate already uses for airlock-return.js, with one difference
# that matters: these two carry their own owner guard. An nginx `if` only covers the
# location it is written in, so a location added beside `location /` inherits nothing
# from it, and the account panel is not a thing to hand to a passing collaborator.
render_devterm_nginx() {
  local GATE_PORT="$1" BACKEND_PORT="$2" PANEL_DIR="${3:-}"
  local extra=""
  if [ -n "$PANEL_DIR" ]; then
    extra="$(mktemp)"
    # QUOTED heredoc + sed placeholder, the convention gate/nginx-lib.sh states and the
    # reason it states it: an unquoted heredoc here would hand `$owner_ok` to the shell,
    # and a backtick in one of these deleted three words from every rendered paseo unit
    # in 2026-08.
    sed -e "s|@@PANEL_DIR@@|${PANEL_DIR}|g" >"$extra" <<'NGINX'

    # platform account panel (hub/assets/accounts) — served here, not by the hub,
    # because accounts.js fetches root-absolute paths on the API's own origin.
    location = /panel.html {
        if ($owner_ok = 0) { return 403; }
        alias @@PANEL_DIR@@/panel.html;
        default_type text/html;
        add_header Cache-Control "no-cache" always;
    }
    location = /accounts.js {
        if ($owner_ok = 0) { return 403; }
        alias @@PANEL_DIR@@/accounts.js;
        default_type application/javascript;
        add_header Cache-Control "no-cache" always;
    }
NGINX
  fi
  echo "# devterm owner gate — generated by apps/devterm/install.sh"
  emit_owner_gate "$GATE_PORT" "127.0.0.1:${BACKEND_PORT}" owner_ok "" "" "$extra"
  [ -n "$extra" ] && rm -f "$extra"
  return 0
}
