# shellcheck shell=bash
# apps/publish/render.sh — sourceable render library (child 4, P1a
# extract-verify-swap). Functions only, no top-level execution. Each
# function body is a VERBATIM copy of the heredoc it replaces, proven
# byte-identical to the inline text by install/test-render-parity.sh before
# any write site moves (P1b).

# render_publish_unit_service BACKEND_PORT SHARE_DIR UPLOADS_DIR IDENTITY_HEADER \
#   INGEST_URL BASE_URL TOKEN_ENV PUBLIC_MODE PUBLIC_DIR STATE_DIR GATED_DIR \
#   HTPASSWD_DIR HTPASSWD_BIN TOKEN_HEADER
render_publish_unit_service() {
  local BACKEND_PORT="$1" SHARE_DIR="$2" UPLOADS_DIR="$3" IDENTITY_HEADER="$4" \
        INGEST_URL="$5" BASE_URL="$6" TOKEN_ENV="$7" PUBLIC_MODE="$8" PUBLIC_DIR="$9"
  shift 9
  local STATE_DIR="$1" GATED_DIR="$2" HTPASSWD_DIR="$3" HTPASSWD_BIN="$4" \
        TOKEN_HEADER="$5"
  local BACKEND_PY="${AIRLOCK_APP_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}/backend/airlock-publish.py"
  cat <<UNIT
[Unit]
Description=airlock publish — static-share manager + uploads (127.0.0.1:${BACKEND_PORT})
After=network.target

[Service]
Type=simple
# Optional secret (the external-publish token) — safe if the file is absent.
EnvironmentFile=-%h/.config/airlock-publish.env
Environment=AIRLOCK_PUBLISH_BACKEND_PORT=${BACKEND_PORT}
Environment=AIRLOCK_PUBLISH_SHARE_DIR=${SHARE_DIR}
Environment=AIRLOCK_PUBLISH_UPLOADS_DIR=${UPLOADS_DIR}
Environment=AIRLOCK_IDENTITY_HEADER=${IDENTITY_HEADER}
Environment=AIRLOCK_PUBLISH_INGEST_URL=${INGEST_URL}
Environment=AIRLOCK_PUBLISH_BASE_URL=${BASE_URL}
Environment=AIRLOCK_PUBLISH_TOKEN_ENV=${TOKEN_ENV}
Environment=AIRLOCK_PUBLISH_PUBLIC_MODE=${PUBLIC_MODE}
Environment=AIRLOCK_PUBLISH_PUBLIC_DIR=${PUBLIC_DIR}
Environment=AIRLOCK_PUBLISH_STATE_DIR=${STATE_DIR}
Environment=AIRLOCK_PUBLISH_GATED_DIR=${GATED_DIR}
Environment=AIRLOCK_PUBLISH_HTPASSWD_DIR=${HTPASSWD_DIR}
Environment=AIRLOCK_PUBLISH_HTPASSWD_BIN=${HTPASSWD_BIN}
Environment=AIRLOCK_PUBLISH_TOKEN_HEADER=${TOKEN_HEADER}
ExecStart=$(command -v python3) ${BACKEND_PY}
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
UNIT
}

# render_publish_unit_cleanup UPLOADS_DIR PUBLIC_MODE PUBLIC_DIR STATE_DIR \
#   GATED_DIR HTPASSWD_DIR HTPASSWD_BIN
render_publish_unit_cleanup() {
  local UPLOADS_DIR="$1" PUBLIC_MODE="$2" PUBLIC_DIR="$3" STATE_DIR="$4" \
        GATED_DIR="$5" HTPASSWD_DIR="$6" HTPASSWD_BIN="$7"
  local BACKEND_PY="${AIRLOCK_APP_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}/backend/airlock-publish.py"
  cat <<UNIT
[Unit]
Description=airlock publish — uploads TTL sweep (24h) + public snapshot expiry

[Service]
Type=oneshot
# MUST mirror the service's public env — the sweep and the writer have to agree
# on which directory and state file they are talking about.
Environment=AIRLOCK_PUBLISH_UPLOADS_DIR=${UPLOADS_DIR}
Environment=AIRLOCK_PUBLISH_PUBLIC_MODE=${PUBLIC_MODE}
Environment=AIRLOCK_PUBLISH_PUBLIC_DIR=${PUBLIC_DIR}
Environment=AIRLOCK_PUBLISH_STATE_DIR=${STATE_DIR}
Environment=AIRLOCK_PUBLISH_GATED_DIR=${GATED_DIR}
Environment=AIRLOCK_PUBLISH_HTPASSWD_DIR=${HTPASSWD_DIR}
Environment=AIRLOCK_PUBLISH_HTPASSWD_BIN=${HTPASSWD_BIN}
ExecStart=$(command -v python3) ${BACKEND_PY} --cleanup
UNIT
}

# render_publish_unit_timer — literal, no args (quoted delimiter, no expansion).
render_publish_unit_timer() {
  cat <<'UNIT'
[Unit]
Description=airlock publish — run uploads TTL sweep hourly

[Timer]
OnBootSec=10min
OnUnitActiveSec=1h
Persistent=true

[Install]
WantedBy=timers.target
UNIT
}

# publish_sed_replacement <value> — escape for safe use as a sed replacement
# (mirrors install.sh's sed_replacement()).
publish_sed_replacement() { printf '%s' "$1" | sed 's/[\\&|]/\\&/g'; }

# render_publish_nginx_main BACKEND_PORT SHARE_DIR
render_publish_nginx_main() {
  local BACKEND_PORT="$1" SHARE_DIR="$2"
  local BACKEND_PORT_SED SHARE_DIR_SED
  BACKEND_PORT_SED="$(publish_sed_replacement "$BACKEND_PORT")"
  SHARE_DIR_SED="$(publish_sed_replacement "$SHARE_DIR")"
  echo "# publish subpath — generated by apps/publish/install.sh"
  sed -e "s|@@BACKEND@@|${BACKEND_PORT_SED}|g" -e "s|@@SHARE@@|${SHARE_DIR_SED}|g" <<'NGINX'
# API backend (backend strips the /publish/ prefix itself). Uploads need a body cap.
location /publish/api/ {
    proxy_pass http://127.0.0.1:@@BACKEND@@;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    client_max_body_size 60m;
    add_header Cache-Control "no-cache" always;
}
# Served static-share directory (hub gate = owner + collaborators, server level).
location /publish/files/ {
    alias @@SHARE@@/;
    autoindex on;
    add_header Cache-Control "no-cache" always;
    # The way out of a document. A home-screen web app has no browser chrome, and
    # these documents are same-origin with the hub, so a reader who opens one is
    # inside the standalone window with no back gesture and no Done button —
    # measured on iPad, 2026-09-02. The legacy box escaped this by accident: it
    # served documents from another port, so iOS treated them as off-scope and lent
    # them ITS chrome.
    #
    # The widget is the platform's shared one, in the same corner mode this app's own
    # page already loads, injected the way the upstream bundles get it (apps/orca,
    # apps/paseo). A published document is exactly the case it was built for: a page
    # nobody can edit — thousands of them, byte-frozen — that still needs a way back.
    # Injecting at serve time also covers a direct link, not just a click from the
    # app. text/html only (sub_filter's default type), so stylesheets and downloads
    # pass through unchanged.
    sub_filter '</body>' '<script src="/airlock-return.js" data-mode="corner" defer></script></body>';
    sub_filter_once on;
}
# Shared document assets at the ROOT path. Documents published into the share dir
# reference their stylesheet and script as ROOT-ABSOLUTE URLs under /_assets/ — that
# is the publishing convention, and thousands of already-published documents encode it.
# Without this location the hub has no /_assets/ route, so the request falls through to
# the SPA index and the browser receives HTML where it asked for CSS. It is a 200, so no
# link checker catches it; the only symptom is that every document renders unstyled
# (measured 2026-09-02: 69,276 bytes of hub HTML in place of a 61,486-byte stylesheet).
# The directory itself is an operator-created symlink inside the share dir.
location /_assets/ {
    alias @@SHARE@@/_assets/;
    add_header Cache-Control "no-cache" always;
}
NGINX
}

# render_publish_nginx_gated_retracted — what remote mode leaves in the gated
# fragment's place. It must be a FILE, not an absence: the README tells the operator
# to `include` this path from THEIR OWN public server block, so deleting it turns
# their config into one that nginx refuses to load. The running nginx keeps serving
# from memory, so nothing looks wrong until the next reload fails — and the next
# restart cannot bring nginx up at all, taking the whole hub with it. Measured on one
# box: `nginx -t` -> [emerg] open() ".../public-includes.d/publish-gated.conf" failed.
#
# Empty of directives, so remote mode serves no gate — the retraction this replaces
# was right about that part, only wrong about how to spell it.
render_publish_nginx_gated_retracted() {
  cat <<'NGINX'
# gated public snapshots — RETRACTED (this box runs publish in remote mode).
#
# Deliberately a file with no directives rather than no file: the public server
# block includes this path, and an include with nothing behind it makes nginx
# refuse to load the whole configuration. Re-installing with
# [apps.publish.public_target].mode = "local" fills this back in.
NGINX
}

# render_publish_nginx_gated GATED_DIR HTPASSWD_DIR — only rendered in PUBLIC_MODE=local.
render_publish_nginx_gated() {
  local GATED_DIR="$1" HTPASSWD_DIR="$2"
  local GATED_DIR_SED HTPASSWD_DIR_SED
  GATED_DIR_SED="$(publish_sed_replacement "$GATED_DIR")"
  HTPASSWD_DIR_SED="$(publish_sed_replacement "$HTPASSWD_DIR")"
  echo "# gated public snapshots — include inside the public nginx server"
  sed -e "s|@@GATED@@|${GATED_DIR_SED}|g" -e "s|@@AUTHDIR@@|${HTPASSWD_DIR_SED}|g" <<'NGINX'
location ~ "^/g/(?<gslug>[a-z0-9][a-z0-9-]{2,63})(?<gpath>/.*)?$" {
    auth_basic "Restricted document";
    auth_basic_user_file @@AUTHDIR@@/$gslug.htpasswd;
    alias @@GATED@@/$gslug$gpath;
    index index.html;
    add_header Cache-Control "no-store" always;
}
NGINX
}
