#!/usr/bin/env python3
"""Atomically replace legacy dev-monitor nginx locations during a cutover.

Every deployment path comes from the environment.  The apply operation retains an
exclusive backup, removes exactly the two legacy API locations from the containing server,
and publishes one included fragment containing the canonical API routes plus the static UI.
It validates the complete nginx configuration and restores both files if validation fails.
"""
from __future__ import annotations

import argparse
import os
from pathlib import Path
import re
import shutil
import stat
import subprocess
import tempfile


class CutoverError(RuntimeError):
    pass


OWNER_RE = re.compile(r'^\s*location\s+/monitor/api/owner/\s*\{\s*(?:#.*)?\Z')
GENERAL_RE = re.compile(r'^\s*location\s+/monitor/api/\s*\{\s*(?:#.*)?\Z')
SERVER_RE = re.compile(r'^\s*server\s*\{\s*(?:#.*)?\Z')


def _brace_delta(line: str) -> int:
    delta = 0
    quote = ''
    escaped = False
    for char in line:
        if escaped:
            escaped = False
            continue
        if quote:
            if char == '\\':
                escaped = True
            elif char == quote:
                quote = ''
            continue
        if char in "'\"":
            quote = char
        elif char == '#':
            break
        elif char == '{':
            delta += 1
        elif char == '}':
            delta -= 1
    return delta


def _block_end(lines: list[str], start: int) -> int:
    depth = 0
    for index in range(start, len(lines)):
        depth += _brace_delta(lines[index])
        if index > start and depth == 0:
            return index + 1
        if depth < 0:
            break
    raise CutoverError(f'unbalanced nginx block beginning at line {start + 1}')


def _blocks(lines: list[str], pattern: re.Pattern[str]) -> list[tuple[int, int]]:
    return [(index, _block_end(lines, index))
            for index, line in enumerate(lines) if pattern.match(line)]


def _server_span(lines: list[str], line_index: int) -> tuple[int, int]:
    candidates = []
    for start, line in enumerate(lines):
        if start > line_index:
            break
        if SERVER_RE.match(line):
            end = _block_end(lines, start)
            if start < line_index < end:
                candidates.append((start, end))
    if len(candidates) != 1:
        raise CutoverError('legacy monitor locations must belong to exactly one server')
    return candidates[0]


def _quote_nginx_path(path: Path) -> str:
    raw = str(path)
    if any(char in raw for char in '\n\r\x00'):
        raise CutoverError('nginx paths must be one line and contain no NUL')
    return '"' + raw.replace('\\', '\\\\').replace('"', '\\"') + '"'


def plan(site_text: str, canonical_text: str, include_dir: Path,
         webroot: Path) -> tuple[str, str]:
    lines = site_text.splitlines(keepends=True)
    owner = _blocks(lines, OWNER_RE)
    general = _blocks(lines, GENERAL_RE)
    if len(owner) != 1 or len(general) != 1:
        raise CutoverError(
            'expected exactly one legacy owner and one legacy general monitor location')
    owner_server = _server_span(lines, owner[0][0])
    general_server = _server_span(lines, general[0][0])
    if owner_server != general_server:
        raise CutoverError('legacy monitor locations are in different servers')

    include_line = f'include {include_dir}/*.conf;'
    server_text = ''.join(lines[owner_server[0]:owner_server[1]])
    if include_line not in (line.strip() for line in server_text.splitlines()):
        raise CutoverError('target server does not include the bridge fragment directory')

    canonical_lines = canonical_text.splitlines()
    if sum(bool(OWNER_RE.match(line)) for line in canonical_lines) != 1:
        raise CutoverError('canonical fragment must contain exactly one owner location')
    if sum(bool(GENERAL_RE.match(line)) for line in canonical_lines) != 1:
        raise CutoverError('canonical fragment must contain exactly one general location')
    if any(re.match(r'^\s*location\s+(?:=\s+)?/monitor(?:/|\s)', line)
           and not (OWNER_RE.match(line) or GENERAL_RE.match(line))
           for line in canonical_lines):
        raise CutoverError('canonical fragment unexpectedly owns the static monitor route')

    for start, end in sorted(owner + general, reverse=True):
        del lines[start:end]
    edited_site = ''.join(lines)
    root = _quote_nginx_path(webroot)
    bridge = canonical_text.rstrip() + f'''

# dev-monitor static UI — generated by install/dev-monitor-cutover-nginx.py
location = /monitor {{
    return 308 /monitor/;
}}
location /monitor/ {{
    root {root};
    try_files $uri $uri/ /monitor/index.html;
}}
'''
    return edited_site, bridge


def _required_path(name: str, *, must_exist: bool = False,
                   directory: bool = False) -> Path:
    raw = os.environ.get(name, '')
    if not raw or any(char in raw for char in '\n\r\x00'):
        raise CutoverError(f'{name} must be an absolute one-line path')
    path = Path(raw)
    if not path.is_absolute():
        raise CutoverError(f'{name} must be an absolute one-line path')
    if path.is_symlink():
        raise CutoverError(f'{name} must not be a symbolic link')
    if must_exist:
        if directory and not path.is_dir():
            raise CutoverError(f'{name} must name an existing directory')
        if not directory and not path.is_file():
            raise CutoverError(f'{name} must name an existing regular file')
    return path.resolve(strict=must_exist)


def _exclusive_copy(source: Path, target: Path) -> None:
    target.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    fd, raw_temp = tempfile.mkstemp(prefix=f'.{target.name}.', dir=target.parent)
    temp = Path(raw_temp)
    try:
        os.fchmod(fd, 0o600)
        with os.fdopen(fd, 'wb', closefd=False) as output, source.open('rb') as inp:
            shutil.copyfileobj(inp, output)
            output.flush()
            os.fsync(output.fileno())
        try:
            os.link(temp, target)
        except FileExistsError as exc:
            raise CutoverError('nginx backup already exists') from exc
        dir_fd = os.open(target.parent, os.O_RDONLY | os.O_DIRECTORY)
        try:
            os.fsync(dir_fd)
        finally:
            os.close(dir_fd)
    finally:
        os.close(fd)
        temp.unlink(missing_ok=True)


def _atomic_write(path: Path, data: str | bytes, *, mode: int,
                  uid: int, gid: int) -> None:
    fd, raw_temp = tempfile.mkstemp(prefix=f'.{path.name}.', dir=path.parent)
    temp = Path(raw_temp)
    try:
        os.fchmod(fd, mode)
        os.fchown(fd, uid, gid)
        payload = data.encode('utf-8') if isinstance(data, str) else data
        with os.fdopen(fd, 'wb', closefd=False) as output:
            output.write(payload)
            output.flush()
            os.fsync(output.fileno())
        os.close(fd)
        fd = -1
        os.replace(temp, path)
        dir_fd = os.open(path.parent, os.O_RDONLY | os.O_DIRECTORY)
        try:
            os.fsync(dir_fd)
        finally:
            os.close(dir_fd)
    finally:
        if fd >= 0:
            os.close(fd)
        temp.unlink(missing_ok=True)


def _nginx_test() -> None:
    nginx = os.environ.get('AIRLOCK_CUTOVER_NGINX_BIN', '/usr/sbin/nginx')
    result = subprocess.run([nginx, '-t'], stdout=subprocess.DEVNULL,
                            stderr=subprocess.DEVNULL, check=False)
    if result.returncode:
        raise CutoverError('nginx configuration validation failed')


def _paths(*, require_webroot: bool = True) -> tuple[Path, Path, Path, Path, Path]:
    site = _required_path('AIRLOCK_CUTOVER_NGINX_SITE', must_exist=True)
    bridge = _required_path('AIRLOCK_CUTOVER_NGINX_BRIDGE')
    include_dir = _required_path(
        'AIRLOCK_CUTOVER_NGINX_INCLUDE_DIR', must_exist=True, directory=True)
    canonical = _required_path(
        'AIRLOCK_CUTOVER_CANONICAL_FRAGMENT', must_exist=True)
    webroot = _required_path('AIRLOCK_CUTOVER_WEBROOT',
                             must_exist=require_webroot, directory=True)
    backup = _required_path('AIRLOCK_CUTOVER_NGINX_BACKUP')
    if bridge.parent.resolve(strict=True) != include_dir:
        raise CutoverError('bridge fragment must be directly inside the include directory')
    if bridge.suffix != '.conf':
        raise CutoverError('bridge fragment must have a .conf suffix')
    if len({site, bridge, canonical, backup}) != 4:
        raise CutoverError('site, bridge, canonical fragment and backup must differ')
    return site, bridge, canonical, webroot, backup


def _rollback_paths() -> tuple[Path, Path, Path]:
    site = _required_path('AIRLOCK_CUTOVER_NGINX_SITE', must_exist=True)
    bridge = _required_path('AIRLOCK_CUTOVER_NGINX_BRIDGE')
    backup = _required_path('AIRLOCK_CUTOVER_NGINX_BACKUP', must_exist=True)
    if len({site, bridge, backup}) != 3:
        raise CutoverError('site, bridge and backup must differ')
    return site, bridge, backup


def apply() -> None:
    site, bridge, canonical, webroot, backup = _paths()
    if bridge.exists() or bridge.is_symlink():
        raise CutoverError('bridge fragment already exists')
    if backup.exists() or backup.is_symlink():
        raise CutoverError('nginx backup already exists')
    site_text = site.read_text(encoding='utf-8')
    canonical_text = canonical.read_text(encoding='utf-8')
    edited_site, bridge_text = plan(site_text, canonical_text, bridge.parent, webroot)
    site_stat = site.stat()
    _exclusive_copy(site, backup)
    pending = bridge.with_name(f'.{bridge.name}.pending')
    if pending.exists() or pending.is_symlink():
        raise CutoverError('pending bridge path already exists')
    try:
        _atomic_write(pending, bridge_text, mode=0o600,
                      uid=site_stat.st_uid, gid=site_stat.st_gid)
        _atomic_write(site, edited_site, mode=stat.S_IMODE(site_stat.st_mode),
                      uid=site_stat.st_uid, gid=site_stat.st_gid)
        os.replace(pending, bridge)
        _nginx_test()
    except Exception as original_error:
        bridge.unlink(missing_ok=True)
        pending.unlink(missing_ok=True)
        _atomic_write(site, backup.read_bytes(), mode=stat.S_IMODE(site_stat.st_mode),
                      uid=site_stat.st_uid, gid=site_stat.st_gid)
        try:
            _nginx_test()
        except Exception as rollback_error:
            raise CutoverError(
                'apply failed and restored nginx configuration did not validate') \
                from rollback_error
        raise original_error
    print('apply=ok legacy_locations_removed=2 backup_retained=1 nginx_test=ok')


def rollback() -> None:
    site, bridge, backup = _rollback_paths()
    site_stat = site.stat()
    hidden = bridge.with_name(f'.{bridge.name}.rollback')
    if hidden.exists() or hidden.is_symlink():
        raise CutoverError('rollback bridge path already exists')
    if bridge.is_symlink():
        raise CutoverError('bridge fragment must not be a symbolic link')
    current_site = site.read_bytes()
    bridge_hidden = False
    try:
        if bridge.exists():
            os.replace(bridge, hidden)
            bridge_hidden = True
        _atomic_write(site, backup.read_bytes(),
                      mode=stat.S_IMODE(site_stat.st_mode),
                      uid=site_stat.st_uid, gid=site_stat.st_gid)
        _nginx_test()
    except Exception as original_error:
        _atomic_write(site, current_site, mode=stat.S_IMODE(site_stat.st_mode),
                      uid=site_stat.st_uid, gid=site_stat.st_gid)
        if bridge_hidden and hidden.exists():
            os.replace(hidden, bridge)
        try:
            _nginx_test()
        except Exception as recovery_error:
            raise CutoverError(
                'rollback failed and the pre-rollback nginx configuration did not validate') \
                from recovery_error
        raise original_error
    if bridge_hidden:
        hidden.unlink(missing_ok=True)
    print('rollback=ok backup_retained=1 nginx_test=ok')


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--plan', action='store_true')
    mode.add_argument('--apply', action='store_true')
    mode.add_argument('--rollback', action='store_true')
    args = parser.parse_args()
    try:
        if args.plan:
            site, bridge, canonical, webroot, _backup = _paths(require_webroot=False)
            plan(site.read_text(encoding='utf-8'),
                 canonical.read_text(encoding='utf-8'), bridge.parent, webroot)
            print('plan=ok legacy_locations=2')
        elif args.apply:
            apply()
        else:
            rollback()
    except (CutoverError, OSError, UnicodeError) as exc:
        print(f'error: {exc}', file=os.sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
