# shellcheck shell=bash
# apps/dev-monitor/render.sh — sourceable render library (child 4, P1a
# extract-verify-swap). Functions only, no top-level execution. Each unit/
# fragment function body is a VERBATIM copy of the heredoc it replaces,
# proven byte-identical to the inline text by install/test-render-parity.sh
# before any write site moves (P1b).

# Shared app boundary: names only, before any generated bytes are emitted.
render_dev_monitor_check_secret_names() {
  python3 "$(dirname "${BASH_SOURCE[0]}")/backend/devmon_secret_names.py" "$@"
}

# render_dev_monitor_env OWNER SECRET STATE CWD SESSION WEBHOOK_NAME CONSOLE_URL
render_dev_monitor_env() {
  local OWNER="$1" DEVMON_SECRET="$2" DEVMON_STATE="$3" EXEC_CWD_ROOT="$4"
  local EXEC_SESSION="$5" SLACK_WEBHOOK_NAME="$6" CONSOLE_URL="${7:-}"
  render_dev_monitor_check_secret_names "$SLACK_WEBHOOK_NAME" || return
  cat <<ENVF
# generated by apps/dev-monitor/install.sh — rewritten on every install
DEV_MONITOR_OWNER=${OWNER}
DEV_MONITOR_PROXY_SECRET=${DEVMON_SECRET}
DEV_MONITOR_SPOOL=${DEVMON_STATE}/spool
DEV_MONITOR_DB=${DEVMON_STATE}/messages.db
DEV_MONITOR_CWD_ROOT=${EXEC_CWD_ROOT}
DEV_MONITOR_EXEC_SESSION=${EXEC_SESSION}
DEVMON_SLACK_WEBHOOK_NAME=${SLACK_WEBHOOK_NAME}
AIRLOCK_DEVMON_CONSOLE_URL=${CONSOLE_URL}
ENVF
}

# render_dev_monitor_owner_env OWNER DEVMON_SECRET
#
# Updates use this minimal ingress gate even when the optional messages spool is
# disabled.  Keep spool/execution/delivery settings out of that off-path file.
render_dev_monitor_owner_env() {
  local OWNER="$1" DEVMON_SECRET="$2"
  cat <<ENVF
# generated owner gate for dev-monitor updates
DEV_MONITOR_OWNER=${OWNER}
DEV_MONITOR_PROXY_SECRET=${DEVMON_SECRET}
ENVF
}

# render_dev_monitor_unit BACKEND_PORT MESSAGES IDENTITY_HEADER cors_origins DEVMON_ENV \
#                         [TOKEN_FRESHNESS TOKEN_WARN_HOURS TOKEN_STALE_HOURS
#                          SPOOL_HARDENING ACCOUNTS_STATUS_BIN AGENT_PROVIDER AGENT_BIN
#                          SLACK_WEBHOOK_NAME AIRLOCK_CONFIG_PATH]
# The token arguments default rather than being required: this function is called by
# install/test-systemd-ordering.sh and by fixtures written before the feature existed,
# and an unset positional under `set -u` would turn a missing argument into an unbound
# variable error rather than the feature simply being off.
render_dev_monitor_unit() {
  local BACKEND_PORT="$1" MESSAGES="$2" IDENTITY_HEADER="$3" cors_origins="$4" DEVMON_ENV="$5"
  local TOKEN_FRESHNESS="${6:-false}" TOKEN_WARN_HOURS="${7:-24}" TOKEN_STALE_HOURS="${8:-24}"
  local SPOOL_HARDENING="${9:-false}" guard=""
  local ACCOUNTS_STATUS_BIN="${10:-${AIRLOCK_ACCOUNTS_STATUS_BIN:-}}"
  # Which agent CLI approved actions run, and the platform CLI that resolves `auto`. Both
  # default rather than being required, for the same reason the token arguments above do:
  # fixtures and install/test-systemd-ordering.sh call this with fewer arguments, and under
  # `set -u` a missing positional would be an unbound-variable error rather than the key
  # simply being unset. Unset here = the backend hands the runner an empty pair = claude.
  local AGENT_PROVIDER="${11:-${AIRLOCK_AGENT_PROVIDER:-}}"
  local AGENT_BIN="${12:-${AIRLOCK_AGENT_BIN:-}}"
  local SLACK_WEBHOOK_NAME="${13:-}"
  # Old fixtures and direct callers stop before this trailing argument. Empty must
  # therefore emit no line at all, preserving the historical unit byte-for-byte.
  # A real install passes the already-resolved original config path; snapshot paths
  # and digests are intentionally install-process-only authority and never land here.
  local AIRLOCK_CONFIG_PATH="${14:-}" AIRLOCK_CONFIG_ENV=""
  if [ -n "$AIRLOCK_CONFIG_PATH" ]; then
    case "$AIRLOCK_CONFIG_PATH" in
      /*) ;;
      *) echo "AIRLOCK_CONFIG_PATH must be absolute" >&2; return 1 ;;
    esac
    case "$AIRLOCK_CONFIG_PATH" in
      *[$'\n\r']*) echo "AIRLOCK_CONFIG_PATH must not contain newlines" >&2; return 1 ;;
    esac
    # Environment= accepts a double-quoted assignment. Escape the unit parser's
    # quoting and specifier characters so even an unusual absolute pathname is one
    # literal environment value rather than another assignment or directive.
    local _config_escaped="$AIRLOCK_CONFIG_PATH"
    _config_escaped="${_config_escaped//\\/\\\\}"
    _config_escaped="${_config_escaped//\"/\\\"}"
    _config_escaped="${_config_escaped//%/%%}"
    AIRLOCK_CONFIG_ENV=$'\nEnvironment="AIRLOCK_CONFIG='"${_config_escaped}"$'"'
  fi
  render_dev_monitor_check_secret_names "$SLACK_WEBHOOK_NAME" || return
  local BACKEND_PY="${AIRLOCK_APP_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}/backend/airlock-dev-monitor.py"
  if [ "$SPOOL_HARDENING" = true ]; then
    guard=$'\nExecStartPre=/usr/bin/systemctl is-active --quiet airlock-dev-monitor-spool-firewall.service'
  fi
  cat <<UNIT
[Unit]
Description=airlock dev-monitor — system observability (127.0.0.1:${BACKEND_PORT})
After=network.target

[Service]
Type=simple
Environment=AIRLOCK_DEV_MONITOR_BACKEND_PORT=${BACKEND_PORT}
Environment=AIRLOCK_DEV_MONITOR_MESSAGES=${MESSAGES}
Environment=AIRLOCK_IDENTITY_HEADER=${IDENTITY_HEADER}
Environment=AIRLOCK_DEV_MONITOR_CORS_ORIGINS=${cors_origins}
Environment=AIRLOCK_DEV_MONITOR_TOKEN_FRESHNESS=${TOKEN_FRESHNESS}
Environment=AIRLOCK_DEV_MONITOR_TOKEN_FRESHNESS_WARN_HOURS=${TOKEN_WARN_HOURS}
Environment=AIRLOCK_DEV_MONITOR_TOKEN_FRESHNESS_STALE_HOURS=${TOKEN_STALE_HOURS}
Environment=AIRLOCK_DEV_MONITOR_ACCOUNTS_STATUS_BIN=${ACCOUNTS_STATUS_BIN}
Environment=AIRLOCK_AGENT_PROVIDER=${AGENT_PROVIDER}
Environment=AIRLOCK_AGENT_BIN=${AGENT_BIN}${AIRLOCK_CONFIG_ENV}
# This 0600 file always carries the update owner's ingress gate. With messages on it
# also carries the optional spool/action configuration; secrets never enter the unit.
EnvironmentFile=-%h/.config/airlock/dev-monitor-secrets.env
EnvironmentFile=-${DEVMON_ENV}
Environment=DEVMON_SLACK_WEBHOOK_NAME=${SLACK_WEBHOOK_NAME}${guard}
ExecStart=$(command -v python3) ${BACKEND_PY}
# always, not on-failure. On 2026-08-27 this backend exited with status 0 on its
# own -- no crash, no stop command -- and on-failure does not restart a clean
# exit, so it simply stayed down. It was down 5h13m before a human noticed, and
# in that window 39 spooled messages (32 of them urgent, from six producers)
# reached nobody: the collector is what drains new/, so nothing it would have
# alerted about was even queued for delivery.
#
# A daemon whose whole job is to notice silence must not be able to leave
# quietly. Restart=always also covers the exit reason we never identified,
# which is
# the point: the restart policy should not depend on our having diagnosed it.
#
# The crash-loop this could mask is caught from outside now: a backend that
# keeps dying does not drain the spool either, and the host's own dead-man
# check reports a new/ that stops emptying. Restart policy and that check are
# a pair; neither is sufficient alone.
Restart=always
RestartSec=3

[Install]
WantedBy=default.target
UNIT
}

# render_dev_monitor_spool_nft WRITER_USER
render_dev_monitor_spool_nft() {
  local WRITER_USER="$1"
  cat <<NFT
# generated by apps/dev-monitor/install-spool-hardening.sh
# The destroy command is idempotent when absent; the whole file is one atomic nft
# transaction, so
# an invalid replacement leaves the prior egress rule in place.
destroy table inet airlock_dev_monitor_spool
table inet airlock_dev_monitor_spool {
  chain output {
    type filter hook output priority 0; policy accept;
    meta skuid "${WRITER_USER}" oifname "lo" accept
    meta skuid "${WRITER_USER}" reject with icmpx type admin-prohibited
  }
}
NFT
}

# render_dev_monitor_spool_firewall_guard WRITER_USER NFT_FILE
render_dev_monitor_spool_firewall_guard() {
  local WRITER_USER="$1" NFT_FILE="$2"
  cat <<GUARD
#!/bin/sh
set -eu
NFT=/usr/sbin/nft
WRITER_UID="\$(/usr/bin/id -u ${WRITER_USER})"
cleanup() {
  "\$NFT" destroy table inet airlock_dev_monitor_spool >/dev/null 2>&1 || true
}
trap cleanup EXIT INT TERM
check_rules() {
  rules="\$("\$NFT" -n list table inet airlock_dev_monitor_spool)"
  printf '%s\n' "\$rules" | /bin/grep -Eq \
    'skuid[[:space:]]+'"\$WRITER_UID"'([^0-9]|$).*oifname[[:space:]]+"lo"[[:space:]]+accept'
  printf '%s\n' "\$rules" | /bin/grep -Eq \
    'skuid[[:space:]]+'"\$WRITER_UID"'([^0-9]|$).*reject'
}
"\$NFT" -f ${NFT_FILE}
check_rules
/usr/bin/systemd-notify --ready
while /bin/sleep 1; do
  check_rules
done
GUARD
}

# render_dev_monitor_spool_firewall_unit
render_dev_monitor_spool_firewall_unit() {
  cat <<UNIT
[Unit]
Description=airlock dev-monitor spool writer egress firewall
DefaultDependencies=no
After=local-fs.target
Before=network-pre.target
Wants=network-pre.target

[Service]
Type=notify
NotifyAccess=all
ExecStart=/opt/airlock/libexec/airlock-dev-monitor-spool-firewall
ExecReload=/usr/sbin/nft -f /etc/airlock/dev-monitor-spool.nft
Restart=on-failure
RestartSec=1
TimeoutStartSec=10

[Install]
WantedBy=multi-user.target
UNIT
}

# render_dev_monitor_owner_location BACKEND_PORT hdr_var DEVMON_SECRET [LOCATION]
render_dev_monitor_owner_location() {
  local BACKEND_PORT="$1" hdr_var="$2" DEVMON_SECRET="$3" LOCATION="${4:-/monitor/api/owner/}"
  cat <<NGXOWNER

location ${LOCATION} {
    proxy_pass http://127.0.0.1:${BACKEND_PORT};
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Devmon-Owner \$http_${hdr_var};
    proxy_set_header X-Devmon-Proxy-Secret "${DEVMON_SECRET}";
    add_header Cache-Control "no-store" always;
}
NGXOWNER
}

# render_dev_monitor_nginx BACKEND_PORT updates_location [additional_owner_locations]
render_dev_monitor_nginx() {
  local BACKEND_PORT="$1" updates_location="$2" owner_locations="${3:-}"
  cat <<EOF
# dev-monitor subpath — generated by apps/dev-monitor/install.sh
# API backend (the backend strips the /monitor/ prefix itself). The UI at
# /monitor/ is served by the hub's static webroot (WEBROOT/monitor/index.html).
# Do not let an installed iOS home-screen webview keep an old dashboard shell
# indefinitely.  The assets may be cached, but every new navigation must revalidate
# the HTML that names their current versions.
location = /monitor/ {
    try_files /monitor/index.html =404;
    add_header Cache-Control "no-cache, no-store, must-revalidate" always;
}
# Compatibility for dashboard shells loaded before the shared Inbox fixed its API
# prefix.  An internal rewrite preserves POST and avoids leaking nginx's loopback
# scheme/port in a redirect; the rewritten request then crosses the existing owner
# gate, so these aliases grant no access themselves.
location = /api/owner/messages { rewrite ^ /monitor\$uri last; }
location ~ ^/api/owner/messages/[^/]+/(read|archive)$ { rewrite ^ /monitor\$uri last; }
location = /api/owner/run { rewrite ^ /monitor\$uri last; }
location = /api/owner/run/window { rewrite ^ /monitor\$uri last; }
location /monitor/api/ {
    proxy_pass http://127.0.0.1:${BACKEND_PORT};
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    # An empty value means nginx does not pass the field at all, so a browser cannot
    # smuggle its own owner/secret in on the observability routes either.
    proxy_set_header X-Devmon-Owner "";
    proxy_set_header X-Devmon-Proxy-Secret "";
    add_header Cache-Control "no-cache" always;
}
${updates_location}${owner_locations}
EOF
}

# render_dev_monitor_heartbeat KIND SPOOL
# Both the installer and the parity harness render these shipped templates.
render_dev_monitor_heartbeat() {
  local kind="$1" spool="$2"
  local appdir="${AIRLOCK_APP_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
  python3 - "$appdir" "$kind" "$spool" "$(command -v python3)" <<'PY'
from pathlib import Path
import sys
appdir, kind, spool, python = sys.argv[1:]
if kind not in ('service', 'timer'):
    raise SystemExit('invalid heartbeat unit kind')
text = (Path(appdir) / 'systemd' / ('airlock-devmon-heartbeat.' + kind + '.in')).read_text()
for token, value in {'APPDIR': appdir, 'SPOOL': spool, 'PYTHON': python}.items():
    # Unit specifiers and quoted command arguments have their own escaping.
    value = value.replace('%', '%%').replace('\\', '\\\\').replace('"', '\\"')
    text = text.replace('@' + token + '@', value)
sys.stdout.write(text)
PY
}
