# shellcheck shell=bash
# apps/dev-monitor/render.sh — sourceable render library (child 4, P1a
# extract-verify-swap). Functions only, no top-level execution. Each unit/
# fragment function body is a VERBATIM copy of the heredoc it replaces,
# proven byte-identical to the inline text by install/test-render-parity.sh
# before any write site moves (P1b).

# render_dev_monitor_env OWNER DEVMON_SECRET DEVMON_STATE EXEC_CWD_ROOT
#                        EXEC_SESSION SLACK_WEBHOOK_URGENT SLACK_WEBHOOK_ROUTINE
#                        CONSOLE_URL
render_dev_monitor_env() {
  local OWNER="$1" DEVMON_SECRET="$2" DEVMON_STATE="$3" EXEC_CWD_ROOT="$4"
  local EXEC_SESSION="$5" SLACK_WEBHOOK_URGENT="$6" SLACK_WEBHOOK_ROUTINE="$7"
  local CONSOLE_URL="$8"
  # The email lane's five, defaulting rather than required — this function is also called by
  # install/test-systemd-ordering.sh and by fixtures written before the lane existed, and an
  # unset positional under `set -u` would turn a missing argument into an unbound variable
  # error rather than the lane simply being off. The roster path (P4) is the same shape one
  # positional later, for the same reason.
  local SMTP_HOST="${9:-}" SMTP_PORT="${10:-}" SMTP_FROM="${11:-}" SMTP_TO="${12:-}"
  local SMTP_USER="${13:-}" SMTP_PASSWORD="${14:-}" ROSTER_PATH="${15:-}"
  cat <<ENVF
# generated by apps/dev-monitor/install.sh — rewritten on every install
DEV_MONITOR_OWNER=${OWNER}
DEV_MONITOR_PROXY_SECRET=${DEVMON_SECRET}
DEV_MONITOR_SPOOL=${DEVMON_STATE}/spool
DEV_MONITOR_DB=${DEVMON_STATE}/messages.db
DEV_MONITOR_CWD_ROOT=${EXEC_CWD_ROOT}
DEV_MONITOR_EXEC_SESSION=${EXEC_SESSION}
AIRLOCK_DEV_MONITOR_SLACK_WEBHOOK_URGENT=${SLACK_WEBHOOK_URGENT}
AIRLOCK_DEV_MONITOR_SLACK_WEBHOOK_ROUTINE=${SLACK_WEBHOOK_ROUTINE}
AIRLOCK_DEVMON_CONSOLE_URL=${CONSOLE_URL}
DEV_MONITOR_SMTP_HOST=${SMTP_HOST}
DEV_MONITOR_SMTP_PORT=${SMTP_PORT}
DEV_MONITOR_SMTP_FROM=${SMTP_FROM}
DEV_MONITOR_SMTP_TO=${SMTP_TO}
DEV_MONITOR_SMTP_USER=${SMTP_USER}
DEV_MONITOR_SMTP_PASSWORD=${SMTP_PASSWORD}
DEV_MONITOR_ROSTER=${ROSTER_PATH}
ENVF
}

# render_dev_monitor_compat_env DEVMON_STATE SLACK_WEBHOOK_URGENT SLACK_WEBHOOK_ROUTINE
#
# A cutover may have producers that still read one operator-declared EnvironmentFile path.
# Keep that bridge deliberately narrower than the backend env: producers need the spool,
# and the independent lane watchdog needs the DB and configured-lane facts. Owner/proxy,
# execution and SMTP values do not belong in this compatibility file.
render_dev_monitor_compat_env() {
  local DEVMON_STATE="$1" SLACK_WEBHOOK_URGENT="$2" SLACK_WEBHOOK_ROUTINE="$3"
  cat <<ENVF
# generated compatibility bridge — contains no owner, proxy, execution or SMTP credentials
DEV_MONITOR_SPOOL=${DEVMON_STATE}/spool
DEV_MONITOR_DB=${DEVMON_STATE}/messages.db
AIRLOCK_DEV_MONITOR_SLACK_WEBHOOK_URGENT=${SLACK_WEBHOOK_URGENT}
AIRLOCK_DEV_MONITOR_SLACK_WEBHOOK_ROUTINE=${SLACK_WEBHOOK_ROUTINE}
ENVF
}

# render_dev_monitor_unit BACKEND_PORT MESSAGES IDENTITY_HEADER cors_hosts DEVMON_ENV \
#                         [TOKEN_FRESHNESS TOKEN_WARN_HOURS TOKEN_STALE_HOURS]
# The token arguments default rather than being required: this function is called by
# install/test-systemd-ordering.sh and by fixtures written before the feature existed,
# and an unset positional under `set -u` would turn a missing argument into an unbound
# variable error rather than the feature simply being off.
render_dev_monitor_unit() {
  local BACKEND_PORT="$1" MESSAGES="$2" IDENTITY_HEADER="$3" cors_hosts="$4" DEVMON_ENV="$5"
  local TOKEN_FRESHNESS="${6:-false}" TOKEN_WARN_HOURS="${7:-24}" TOKEN_STALE_HOURS="${8:-24}"
  local SPOOL_HARDENING="${9:-false}" guard=""
  local BACKEND_PY="${AIRLOCK_APP_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}/backend/airlock-dev-monitor.py"
  if [ "$SPOOL_HARDENING" = true ]; then
    guard=$'\nExecStartPre=/usr/bin/systemctl is-active --quiet airlock-dev-monitor-spool-firewall.service'
  fi
  cat <<UNIT
[Unit]
Description=airlock dev-monitor — system observability (127.0.0.1:${BACKEND_PORT})
After=network.target

[Service]
Type=simple
Environment=AIRLOCK_DEV_MONITOR_BACKEND_PORT=${BACKEND_PORT}
Environment=AIRLOCK_DEV_MONITOR_MESSAGES=${MESSAGES}
Environment=AIRLOCK_IDENTITY_HEADER=${IDENTITY_HEADER}
Environment=AIRLOCK_DEV_MONITOR_CORS_HOSTS=${cors_hosts}
Environment=AIRLOCK_DEV_MONITOR_TOKEN_FRESHNESS=${TOKEN_FRESHNESS}
Environment=AIRLOCK_DEV_MONITOR_TOKEN_FRESHNESS_WARN_HOURS=${TOKEN_WARN_HOURS}
Environment=AIRLOCK_DEV_MONITOR_TOKEN_FRESHNESS_STALE_HOURS=${TOKEN_STALE_HOURS}
# '-' = optional: with messages off the file is absent by design, and the backend
# then serves observability only. Secrets stay in this 0600 file, out of the unit.
EnvironmentFile=-${DEVMON_ENV}${guard}
ExecStart=$(command -v python3) ${BACKEND_PY}
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
UNIT
}

# render_dev_monitor_spool_nft WRITER_USER
render_dev_monitor_spool_nft() {
  local WRITER_USER="$1"
  cat <<NFT
# generated by apps/dev-monitor/install-spool-hardening.sh
# The destroy command is idempotent when absent; the whole file is one atomic nft
# transaction, so
# an invalid replacement leaves the prior egress rule in place.
destroy table inet airlock_dev_monitor_spool
table inet airlock_dev_monitor_spool {
  chain output {
    type filter hook output priority 0; policy accept;
    meta skuid "${WRITER_USER}" oifname "lo" accept
    meta skuid "${WRITER_USER}" reject with icmpx type admin-prohibited
  }
}
NFT
}

# render_dev_monitor_spool_firewall_guard WRITER_USER NFT_FILE
render_dev_monitor_spool_firewall_guard() {
  local WRITER_USER="$1" NFT_FILE="$2"
  cat <<GUARD
#!/bin/sh
set -eu
NFT=/usr/sbin/nft
WRITER_UID="\$(/usr/bin/id -u ${WRITER_USER})"
cleanup() {
  "\$NFT" destroy table inet airlock_dev_monitor_spool >/dev/null 2>&1 || true
}
trap cleanup EXIT INT TERM
check_rules() {
  rules="\$("\$NFT" -n list table inet airlock_dev_monitor_spool)"
  printf '%s\n' "\$rules" | /bin/grep -Eq \
    'skuid[[:space:]]+'"\$WRITER_UID"'([^0-9]|$).*oifname[[:space:]]+"lo"[[:space:]]+accept'
  printf '%s\n' "\$rules" | /bin/grep -Eq \
    'skuid[[:space:]]+'"\$WRITER_UID"'([^0-9]|$).*reject'
}
"\$NFT" -f ${NFT_FILE}
check_rules
/usr/bin/systemd-notify --ready
while /bin/sleep 1; do
  check_rules
done
GUARD
}

# render_dev_monitor_spool_firewall_unit
render_dev_monitor_spool_firewall_unit() {
  cat <<UNIT
[Unit]
Description=airlock dev-monitor spool writer egress firewall
DefaultDependencies=no
After=local-fs.target
Before=network-pre.target
Wants=network-pre.target

[Service]
Type=notify
NotifyAccess=all
ExecStart=/opt/airlock/libexec/airlock-dev-monitor-spool-firewall
ExecReload=/usr/sbin/nft -f /etc/airlock/dev-monitor-spool.nft
Restart=on-failure
RestartSec=1
TimeoutStartSec=10

[Install]
WantedBy=multi-user.target
UNIT
}

# render_dev_monitor_owner_location BACKEND_PORT hdr_var DEVMON_SECRET
render_dev_monitor_owner_location() {
  local BACKEND_PORT="$1" hdr_var="$2" DEVMON_SECRET="$3"
  cat <<NGXOWNER

location /monitor/api/owner/ {
    proxy_pass http://127.0.0.1:${BACKEND_PORT};
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Devmon-Owner \$http_${hdr_var};
    proxy_set_header X-Devmon-Proxy-Secret "${DEVMON_SECRET}";
    add_header Cache-Control "no-store" always;
}
NGXOWNER
}

# render_dev_monitor_nginx BACKEND_PORT owner_location
render_dev_monitor_nginx() {
  local BACKEND_PORT="$1" owner_location="$2"
  cat <<EOF
# dev-monitor subpath — generated by apps/dev-monitor/install.sh
# API backend (the backend strips the /monitor/ prefix itself). The UI at
# /monitor/ is served by the hub's static webroot (WEBROOT/monitor/index.html).
location /monitor/api/ {
    proxy_pass http://127.0.0.1:${BACKEND_PORT};
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    # An empty value means nginx does not pass the field at all, so a browser cannot
    # smuggle its own owner/secret in on the observability routes either.
    proxy_set_header X-Devmon-Owner "";
    proxy_set_header X-Devmon-Proxy-Secret "";
    add_header Cache-Control "no-cache" always;
}
${owner_location}
EOF
}
